import { useState } from "react";
import { Link } from "react-router-dom";
import { api, SLOTS } from "~/lib/api";
import { ApiError } from "~/lib/http";
import { money, normalisePhone, timeLabel } from "~/lib/format";
import { pointsOffer } from "~/lib/loyalty";
import { useAction, useResource } from "~/lib/useResource";
import { Button, IconButton, LinkButton } from "~/ui/Button";
import { PhoneField, SelectField, Switch, TextAreaField, TextField } from "~/ui/Field";
import { Icon } from "~/ui/Icon";
import { Photo } from "~/ui/Photo";
import { Money } from "~/ui/Bits";
import { EmptyState, ErrorState, Notice, SkeletonCards } from "~/ui/Feedback";
import { useBasket } from "~/state/basket";
import { useSession } from "~/state/session";
import { useToast } from "~/state/toast";
import { MomoDialog } from "~/features/pay/MomoDialog";

interface Placed { order_no: string; total_fcfa: number; discount_fcfa: number; points_spent: number; points_value_fcfa: number; payment_required: boolean; }

export function OrderPage() {
  const { user } = useSession(); const basket = useBasket(); const toast = useToast();
  const menu = useResource(() => api.site.menu(), []); const loyalty = useResource(() => (user ? api.me.loyalty() : Promise.resolve(null)), [user?.id]);
  const [name, setName] = useState(user?.name ?? ""); const [phone, setPhone] = useState(""); const [pickup, setPickup] = useState(SLOTS[8] ?? "13:00"); const [note, setNote] = useState(""); const [promo, setPromo] = useState(""); const [gift, setGift] = useState(""); const [usePoints, setUsePoints] = useState(true); const [problem, setProblem] = useState<string | null>(null);
  const [placed, setPlaced] = useState<Placed | null>(null); const [ordered, setOrdered] = useState<{ name: string; qty: number; total: number }[]>([]); const [paying, setPaying] = useState(false); const [collected, setCollected] = useState(false);
  const place = useAction(api.orders.place);

  if (menu.loading) return <div className="page section"><SkeletonCards count={3} height="6rem" /></div>;
  if (menu.error) return <div className="page section"><ErrorState error={menu.error} onRetry={menu.reload} /></div>;

  const { lines, subtotal, dropped } = basket.price(menu.data ?? []);
  const offer = pointsOffer(loyalty.data, subtotal); const pointsOff = offer && usePoints ? offer.value : 0; const dueNow = Math.max(0, subtotal - pointsOff);

  if (collected && placed) return <div className="page section stack stack--loose" style={{ maxWidth: "34rem" }}><div className="section-head"><hr className="heat-rule" /><h1 className="display display--xl">Order in</h1></div><div className="pass"><header className="pass__head"><span className="badge badge--good">Sent to the kitchen</span><span className="pass__table">Collect at <strong>{timeLabel(pickup)}</strong></span></header><div className="pass__tear" aria-hidden="true"><span /><span /></div><footer className="pass__foot"><div><span className="label">Show this at the counter</span><p className="pass__code mono">{placed.order_no}</p></div></footer>{ordered.length > 0 ? <div className="stack stack--tight"><span className="label">Your order</span><ul className="lines">{ordered.map((line) => <li key={line.name}><span className="mono lines__qty">{line.qty}</span><span>{line.name}</span><Money value={line.total} className="push" /></li>)}</ul>{placed.points_spent > 0 ? <div className="row row--between"><span className="muted">Points used</span><span className="fine">{placed.points_spent} points, - <Money value={placed.points_value_fcfa} /></span></div> : null}<div className="row row--between total-row"><strong>Paid</strong><strong><Money value={placed.total_fcfa} /></strong></div></div> : null}<p className="fine muted">We start cooking closer to the time so it is hot when you arrive. {user ? "Your code and this list are also saved in Mine." : "Write the code down: you ordered without an account, so this page is the only copy."}</p></div><div className="row row--wrap"><LinkButton to="/mine" tone="primary" iconEnd="arrow-right">See my orders</LinkButton><LinkButton to="/menu" tone="ghost">Order more</LinkButton></div></div>;

  if (lines.length === 0) return <div className="page section"><div className="section-head"><hr className="heat-rule" /><h1 className="display display--xl">Your basket</h1></div><EmptyState icon="basket" title="Nothing in it yet" action={<LinkButton to="/menu" tone="primary">Go to the menu</LinkButton>}>Add what you want from the menu, then pick a collection time here.</EmptyState></div>;

  async function submit() {
    setProblem(null); const digits = normalisePhone(phone); if (name.trim().length < 2) { setProblem("Enter the name we should call out."); return; } if (digits.length < 8) { setProblem("Enter a phone number we can reach you on."); return; }
    const result = await place.run({ name: name.trim(), phone: digits, pickup_time: pickup, items: lines.map((line) => ({ id: line.id, qty: line.qty })), note: note.trim() || undefined, promo_code: user && promo.trim() ? promo.trim() : undefined, gift_card_code: user && gift.trim() ? gift.trim() : undefined, use_points: Boolean(offer) && usePoints });
    if (!result) { const failure = place.readError(); setProblem(failure instanceof ApiError ? failure.message : "That order could not be sent."); return; }
    setOrdered(lines.map((line) => ({ name: line.item.name, qty: line.qty, total: line.lineTotal }))); setPlaced(result);
    if (result.payment_required) setPaying(true); else { basket.clear(); setCollected(true); }
  }

  return <div className="page section"><div className="section-head"><hr className="heat-rule" /><h1 className="display display--xl">Your basket</h1></div><div className="checkout"><section className="stack stack--loose">{dropped > 0 ? <Notice tone="warn">{dropped === 1 ? "An item" : `${dropped} items`} came off the menu since you added it, so it is no longer in the basket.</Notice> : null}<ul className="basket">{lines.map((line) => <li key={line.id} className="basket__line"><Photo className="basket__photo" src={line.item.image_url} alt="" /><div className="basket__body"><p className="basket__name">{line.item.name}</p><p className="fine faint"><Money value={line.item.price_fcfa ?? 0} /> each</p></div><div className="counter" role="group" aria-label={`Quantity, ${line.item.name}`}><button type="button" className="counter__btn" onClick={() => basket.setQty(line.id, line.qty - 1)} aria-label={`One fewer ${line.item.name}`}><Icon name="minus" size={16} /></button><span className="counter__value">{line.qty}</span><button type="button" className="counter__btn" onClick={() => basket.setQty(line.id, line.qty + 1)} disabled={line.qty >= 20} aria-label={`One more ${line.item.name}`}><Icon name="plus" size={16} /></button></div><Money value={line.lineTotal} className="basket__total" /><IconButton name="trash" label={`Remove ${line.item.name}`} size="sm" onClick={() => basket.remove(line.id)} /></li>)}</ul>
    <div className="stack" style={{ maxWidth: "32rem" }}><h2 className="display display--lg">Who is collecting</h2><TextField label="Name for the order" hint="What we call out at the counter." value={name} autoComplete="name" onChange={(e) => setName(e.target.value)} required /><PhoneField label="Phone number" hint="We call this number if there is a question about your order." value={phone} onChange={setPhone} required /><SelectField label="Collection time" hint="Give us at least half an hour. Everything is grilled fresh when you order it." value={pickup} onChange={(e) => setPickup(e.target.value)}>{SLOTS.map((slot) => <option key={slot} value={slot}>{slot}</option>)}</SelectField><TextAreaField label="Anything to add" placeholder="Optional. Extra pepper, no onions, that sort of thing." maxLength={300} value={note} onChange={(e) => setNote(e.target.value)} />{offer ? <Switch checked={usePoints} onChange={setUsePoints} label={<>Use {offer.points} points, <Money value={offer.value} /> off</>} /> : null}{user ? <div className="grid--two"><TextField label="Promo code" placeholder="Optional" value={promo} autoCapitalize="characters" onChange={(e) => setPromo(e.target.value)} /><TextField label="Gift card" placeholder="Optional" value={gift} autoCapitalize="characters" onChange={(e) => setGift(e.target.value)} /></div> : <p className="fine faint"><Link to="/signin" state={{ from: "/order" }}>Sign in</Link> to use a promo code or a gift card, and to keep your orders in one place.</p>}</div></section>
    <aside className="checkout__side"><div className="card stack"><div className="row row--between"><span className="muted">Subtotal</span><Money value={subtotal} /></div><div className="row row--between"><span className="muted">Takeaway</span><span className="fine">Free</span></div>{pointsOff > 0 ? <div className="row row--between"><span className="muted">Points</span><span className="fine">- <Money value={pointsOff} /></span></div> : null}<div className="row row--between total-row"><strong>To pay</strong><strong className="checkout__total"><Money value={dueNow} /></strong></div><p className="fine faint">Pay securely with MTN Mobile Money or Orange Money. No card payment is used.</p>{problem ? <Notice tone="bad">{problem}</Notice> : null}<Button tone="primary" size="lg" block className="checkout__pay" busy={place.busy} onClick={submit} icon="wallet">Pay {money(dueNow)} FCFA</Button></div></aside></div>
    <div className="basket-bar basket-bar--phone"><div className="page row row--between"><span className="stack stack--tight"><span className="label">To pay</span><strong className="basket-bar__total">{money(dueNow)} FCFA</strong></span><Button tone="primary" busy={place.busy} onClick={submit} icon="wallet">Pay {money(dueNow)} FCFA</Button></div></div>
    {placed ? <MomoDialog open={paying} amountFcfa={placed.total_fcfa} title="Pay for your order" what={`Order ${placed.order_no}, collect at ${timeLabel(pickup)}`} driver={{ start: (input) => api.orders.pay(placed.order_no, input.momoPhone, input.wallet, input.idempotencyKey).then((prompt) => ({ reference: prompt.reference, amount_fcfa: prompt.amount_fcfa, expires_in_seconds: prompt.expires_in_seconds, payment_url: prompt.payment_url })), poll: api.orders.paymentStatus, abandon: api.orders.abandonPayment }} onClose={() => { setPaying(false); basket.clear(); toast.say(user ? `Order ${placed.order_no} is saved. Pay for it in Mine so the kitchen can start.` : `Order ${placed.order_no} was not paid, so the kitchen has not started on it. Order again when you are ready to pay.`); setCollected(true); }} onPaid={() => { setPaying(false); basket.clear(); setCollected(true); }} /> : null}
  </div>;
}
